"""Add user_tokens expires_at col index

Revision ID: 34e2c14ffc9d
Revises: 64ae474748a7
Create Date: 2024-06-30 19:22:35.055618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34e2c14ffc9d'
down_revision: Union[str, None] = '64ae474748a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tokens_is_revoked', table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_expires_at'), 'user_tokens', ['expires_at'], unique=False)
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('user_tokens', 'is_revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated uby Alembic - please adjust! ###
    op.add_column(
        'user_tokens',
        sa.Column('is_revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_user_tokens_expires_at'), table_name='user_tokens')
    op.create_index('ix_user_tokens_is_revoked', 'user_tokens', ['is_revoked'], unique=False)
    # ### end Alembic commands ###
