"""Add user_tokens table expires_at doc

Revision ID: 851bfbcfcdcf
Revises: c9f1b7d96467
Create Date: 2024-06-21 18:32:02.497885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '851bfbcfcdcf'
down_revision: Union[str, None] = 'c9f1b7d96467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_tokens',
        'expires_at',
        existing_type=mysql.DATETIME(),
        comment='refrehs token expires time',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_tokens',
        'expires_at',
        existing_type=mysql.DATETIME(),
        comment=None,
        existing_comment='refrehs token expires time',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
