"""Edit user_tokens table column

Revision ID: c9f1b7d96467
Revises: fd0ff0dc851b
Create Date: 2024-06-20 21:09:19.236820

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9f1b7d96467'
down_revision: Union[str, None] = 'fd0ff0dc851b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('access_key', sa.String(length=255), nullable=True))
    op.add_column('user_tokens', sa.Column('refresh_key', sa.String(length=255), nullable=True))
    op.drop_index('ix_user_tokens_access_token', table_name='user_tokens')
    op.drop_index('ix_user_tokens_refresh_token', table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_access_key'), 'user_tokens', ['access_key'], unique=False)
    op.create_index(
        op.f('ix_user_tokens_refresh_key'), 'user_tokens', ['refresh_key'], unique=False
    )
    op.drop_column('user_tokens', 'refresh_token')
    op.drop_column('user_tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_tokens', sa.Column('access_token', mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column(
        'user_tokens', sa.Column('refresh_token', mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_index(op.f('ix_user_tokens_refresh_key'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_access_key'), table_name='user_tokens')
    op.create_index('ix_user_tokens_refresh_token', 'user_tokens', ['refresh_token'], unique=False)
    op.create_index('ix_user_tokens_access_token', 'user_tokens', ['access_token'], unique=False)
    op.drop_column('user_tokens', 'refresh_key')
    op.drop_column('user_tokens', 'access_key')
    # ### end Alembic commands ###
