"""Create user tokens tables

Revision ID: fd0ff0dc851b
Revises: bdc54353d9b4
Create Date: 2024-06-20 00:10:47.616123

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fd0ff0dc851b'
down_revision: Union[str, None] = 'bdc54353d9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('access_token', sa.String(length=255), nullable=True),
        sa.Column('refresh_token', sa.String(length=255), nullable=True),
        sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_user_tokens_access_token'), 'user_tokens', ['access_token'], unique=False
    )
    op.create_index(
        op.f('ix_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_refresh_token'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_access_token'), table_name='user_tokens')
    op.drop_table('user_tokens')
    # ### end Alembic commands ###
