"""Redesign user_tokens table

Revision ID: 64ae474748a7
Revises: e5d749d2f605
Create Date: 2024-06-30 01:48:18.990781

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64ae474748a7'
down_revision: Union[str, None] = 'e5d749d2f605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('token_key', sa.String(length=255), nullable=True))
    op.add_column('user_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.add_column('user_tokens', sa.Column('purpose', sa.String(length=20), nullable=False))
    op.alter_column(
        'user_tokens',
        'expires_at',
        existing_type=mysql.DATETIME(),
        comment='token expires time',
        existing_comment='refrehs token expires time',
        existing_nullable=False,
    )
    op.drop_index('ix_user_tokens_access_key', table_name='user_tokens')
    op.drop_index('ix_user_tokens_refresh_key', table_name='user_tokens')
    op.drop_constraint('user_tokens_ibfk_1', 'user_tokens', type_='foreignkey')
    op.drop_index('user_id', table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_is_revoked'), 'user_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_user_tokens_token_key'), 'user_tokens', ['token_key'], unique=False)
    op.drop_column('user_tokens', 'refresh_key')
    op.drop_column('user_tokens', 'access_key')
    op.drop_column('user_tokens', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('user_tokens', sa.Column('access_key', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user_tokens', sa.Column('refresh_key', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_user_tokens_token_key'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_is_revoked'), table_name='user_tokens')
    op.create_index('user_id', 'user_tokens', ['user_id'], unique=True)
    op.create_foreign_key('user_tokens_ibfk_1', 'user_tokens', 'users', ['user_id'], ['id'])
    op.create_index('ix_user_tokens_refresh_key', 'user_tokens', ['refresh_key'], unique=False)
    op.create_index('ix_user_tokens_access_key', 'user_tokens', ['access_key'], unique=False)
    op.alter_column(
        'user_tokens',
        'expires_at',
        existing_type=mysql.DATETIME(),
        comment='refrehs token expires time',
        existing_comment='token expires time',
        existing_nullable=False,
    )
    op.drop_column('user_tokens', 'purpose')
    op.drop_column('user_tokens', 'is_revoked')
    op.drop_column('user_tokens', 'token_key')
    # ### end Alembic commands ###
